# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_msg/auto_dockFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class auto_dockFeedback(genpy.Message):
  _md5sum = "3a59dd52073742794fd7cc52d1917f2d"
  _type = "robot_msg/auto_dockFeedback"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Define a feedback message
# constants state enum
uint8 NONE              = 0 #初始化状态
uint8 SEARCHING_STATION = 1 # 1-寻找充电桩
uint8 DOCKING_STATION   = 2 # 2-对接中
uint8 DOCKING_SUCCESS   = 3 # 3-对接成功
uint8 SEPERATING        = 4 # 4-脱离中
uint8 SEPERATING_DONE   = 5 # 5-脱离成功
uint8 SEARCHING_FAILURE = 6 # 6-失败-未找到充电桩
uint8 DOCKING_FAILURE   = 7 # 7-失败-对接失败
uint8 SEPERAT_FAILURE   = 8 # 8-失败-脱离失败
uint8 CANCLED           = 9 # 9-成功-动作被取消

uint8 dock_feedback
string dock_feedback_text

"""
  # Pseudo-constants
  NONE = 0
  SEARCHING_STATION = 1
  DOCKING_STATION = 2
  DOCKING_SUCCESS = 3
  SEPERATING = 4
  SEPERATING_DONE = 5
  SEARCHING_FAILURE = 6
  DOCKING_FAILURE = 7
  SEPERAT_FAILURE = 8
  CANCLED = 9

  __slots__ = ['dock_feedback','dock_feedback_text']
  _slot_types = ['uint8','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dock_feedback,dock_feedback_text

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(auto_dockFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.dock_feedback is None:
        self.dock_feedback = 0
      if self.dock_feedback_text is None:
        self.dock_feedback_text = ''
    else:
      self.dock_feedback = 0
      self.dock_feedback_text = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.dock_feedback
      buff.write(_get_struct_B().pack(_x))
      _x = self.dock_feedback_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.dock_feedback,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dock_feedback_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dock_feedback_text = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.dock_feedback
      buff.write(_get_struct_B().pack(_x))
      _x = self.dock_feedback_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.dock_feedback,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dock_feedback_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.dock_feedback_text = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
