// Generated by gencpp from file forward_server/forwardFeedback.msg
// DO NOT EDIT!


#ifndef FORWARD_SERVER_MESSAGE_FORWARDFEEDBACK_H
#define FORWARD_SERVER_MESSAGE_FORWARDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace forward_server
{
template <class ContainerAllocator>
struct forwardFeedback_
{
  typedef forwardFeedback_<ContainerAllocator> Type;

  forwardFeedback_()
    : fdbk(0.0)  {
    }
  forwardFeedback_(const ContainerAllocator& _alloc)
    : fdbk(0.0)  {
  (void)_alloc;
    }



   typedef double _fdbk_type;
  _fdbk_type fdbk;





  typedef boost::shared_ptr< ::forward_server::forwardFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::forward_server::forwardFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct forwardFeedback_

typedef ::forward_server::forwardFeedback_<std::allocator<void> > forwardFeedback;

typedef boost::shared_ptr< ::forward_server::forwardFeedback > forwardFeedbackPtr;
typedef boost::shared_ptr< ::forward_server::forwardFeedback const> forwardFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::forward_server::forwardFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::forward_server::forwardFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace forward_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'forward_server': ['/home/zhx/zk/learn_action/devel/share/forward_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::forward_server::forwardFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::forward_server::forwardFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::forward_server::forwardFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::forward_server::forwardFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forward_server::forwardFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::forward_server::forwardFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::forward_server::forwardFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b943316533599dac5500906be44744f1";
  }

  static const char* value(const ::forward_server::forwardFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb943316533599dacULL;
  static const uint64_t static_value2 = 0x5500906be44744f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::forward_server::forwardFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "forward_server/forwardFeedback";
  }

  static const char* value(const ::forward_server::forwardFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::forward_server::forwardFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
float64 fdbk\n\
\n\
\n\
";
  }

  static const char* value(const ::forward_server::forwardFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::forward_server::forwardFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fdbk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct forwardFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::forward_server::forwardFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::forward_server::forwardFeedback_<ContainerAllocator>& v)
  {
    s << indent << "fdbk: ";
    Printer<double>::stream(s, indent + "  ", v.fdbk);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORWARD_SERVER_MESSAGE_FORWARDFEEDBACK_H
