// Generated by gencpp from file robot_msg/auto_dockActionFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_AUTO_DOCKACTIONFEEDBACK_H
#define ROBOT_MSG_MESSAGE_AUTO_DOCKACTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalStatus.h>
#include <robot_msg/auto_dockFeedback.h>

namespace robot_msg
{
template <class ContainerAllocator>
struct auto_dockActionFeedback_
{
  typedef auto_dockActionFeedback_<ContainerAllocator> Type;

  auto_dockActionFeedback_()
    : header()
    , status()
    , feedback()  {
    }
  auto_dockActionFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)
    , feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalStatus_<ContainerAllocator>  _status_type;
  _status_type status;

   typedef  ::robot_msg::auto_dockFeedback_<ContainerAllocator>  _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct auto_dockActionFeedback_

typedef ::robot_msg::auto_dockActionFeedback_<std::allocator<void> > auto_dockActionFeedback;

typedef boost::shared_ptr< ::robot_msg::auto_dockActionFeedback > auto_dockActionFeedbackPtr;
typedef boost::shared_ptr< ::robot_msg::auto_dockActionFeedback const> auto_dockActionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator1> & lhs, const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator1> & lhs, const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a07b3b424009a3a550b25706e3fdc432";
  }

  static const char* value(const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa07b3b424009a3a5ULL;
  static const uint64_t static_value2 = 0x50b25706e3fdc432ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/auto_dockActionFeedback";
  }

  static const char* value(const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"auto_dockFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_msg/auto_dockFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"# constants state enum\n"
"uint8 NONE              = 0 #初始化状态\n"
"uint8 SEARCHING_STATION = 1 # 1-寻找充电桩\n"
"uint8 DOCKING_STATION   = 2 # 2-对接中\n"
"uint8 DOCKING_SUCCESS   = 3 # 3-对接成功\n"
"uint8 SEPERATING        = 4 # 4-脱离中\n"
"uint8 SEPERATING_DONE   = 5 # 5-脱离成功\n"
"uint8 SEARCHING_FAILURE = 6 # 6-失败-未找到充电桩\n"
"uint8 DOCKING_FAILURE   = 7 # 7-失败-对接失败\n"
"uint8 SEPERAT_FAILURE   = 8 # 8-失败-脱离失败\n"
"uint8 CANCLED           = 9 # 9-成功-动作被取消\n"
"\n"
"uint8 dock_feedback\n"
"string dock_feedback_text\n"
"\n"
;
  }

  static const char* value(const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct auto_dockActionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::auto_dockActionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::auto_dockActionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    s << indent << "feedback: ";
    s << std::endl;
    Printer< ::robot_msg::auto_dockFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_AUTO_DOCKACTIONFEEDBACK_H
