// Generated by gencpp from file robot_msg/CartoToVisionMap.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_CARTOTOVISIONMAP_H
#define ROBOT_MSG_MESSAGE_CARTOTOVISIONMAP_H

#include <ros/service_traits.h>


#include <robot_msg/CartoToVisionMapRequest.h>
#include <robot_msg/CartoToVisionMapResponse.h>


namespace robot_msg
{

struct CartoToVisionMap
{

typedef CartoToVisionMapRequest Request;
typedef CartoToVisionMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CartoToVisionMap
} // namespace robot_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msg::CartoToVisionMap > {
  static const char* value()
  {
    return "19a9e8c96780c7c67a6911545c02145e";
  }

  static const char* value(const ::robot_msg::CartoToVisionMap&) { return value(); }
};

template<>
struct DataType< ::robot_msg::CartoToVisionMap > {
  static const char* value()
  {
    return "robot_msg/CartoToVisionMap";
  }

  static const char* value(const ::robot_msg::CartoToVisionMap&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msg::CartoToVisionMapRequest> should match
// service_traits::MD5Sum< ::robot_msg::CartoToVisionMap >
template<>
struct MD5Sum< ::robot_msg::CartoToVisionMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::CartoToVisionMap >::value();
  }
  static const char* value(const ::robot_msg::CartoToVisionMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::CartoToVisionMapRequest> should match
// service_traits::DataType< ::robot_msg::CartoToVisionMap >
template<>
struct DataType< ::robot_msg::CartoToVisionMapRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msg::CartoToVisionMap >::value();
  }
  static const char* value(const ::robot_msg::CartoToVisionMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msg::CartoToVisionMapResponse> should match
// service_traits::MD5Sum< ::robot_msg::CartoToVisionMap >
template<>
struct MD5Sum< ::robot_msg::CartoToVisionMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::CartoToVisionMap >::value();
  }
  static const char* value(const ::robot_msg::CartoToVisionMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::CartoToVisionMapResponse> should match
// service_traits::DataType< ::robot_msg::CartoToVisionMap >
template<>
struct DataType< ::robot_msg::CartoToVisionMapResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msg::CartoToVisionMap >::value();
  }
  static const char* value(const ::robot_msg::CartoToVisionMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_CARTOTOVISIONMAP_H
