// Generated by gencpp from file robot_msg/CartoToVisionMapRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_CARTOTOVISIONMAPREQUEST_H
#define ROBOT_MSG_MESSAGE_CARTOTOVISIONMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace robot_msg
{
template <class ContainerAllocator>
struct CartoToVisionMapRequest_
{
  typedef CartoToVisionMapRequest_<ContainerAllocator> Type;

  CartoToVisionMapRequest_()
    : map_flag(false)
    , poses()  {
    }
  CartoToVisionMapRequest_(const ContainerAllocator& _alloc)
    : map_flag(false)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _map_flag_type;
  _map_flag_type map_flag;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CartoToVisionMapRequest_

typedef ::robot_msg::CartoToVisionMapRequest_<std::allocator<void> > CartoToVisionMapRequest;

typedef boost::shared_ptr< ::robot_msg::CartoToVisionMapRequest > CartoToVisionMapRequestPtr;
typedef boost::shared_ptr< ::robot_msg::CartoToVisionMapRequest const> CartoToVisionMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator1> & lhs, const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_flag == rhs.map_flag &&
    lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator1> & lhs, const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9995b66cc422aa881fe02843d00db5f5";
  }

  static const char* value(const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9995b66cc422aa88ULL;
  static const uint64_t static_value2 = 0x1fe02843d00db5f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/CartoToVisionMapRequest";
  }

  static const char* value(const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool map_flag  # true-发送建图请求\n"
"geometry_msgs/PoseStamped[] poses # 激光雷达所有scan帧的时间戳和位姿(雷达到世界坐标系)\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_flag);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartoToVisionMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::CartoToVisionMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.map_flag);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_CARTOTOVISIONMAPREQUEST_H
