// Generated by gencpp from file robot_msg/LeanMap.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_LEANMAP_H
#define ROBOT_MSG_MESSAGE_LEANMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msg
{
template <class ContainerAllocator>
struct LeanMap_
{
  typedef LeanMap_<ContainerAllocator> Type;

  LeanMap_()
    : resolution(0.0)
    , width(0)
    , height(0)
    , data()  {
    }
  LeanMap_(const ContainerAllocator& _alloc)
    : resolution(0.0)
    , width(0)
    , height(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef float _resolution_type;
  _resolution_type resolution;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::robot_msg::LeanMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::LeanMap_<ContainerAllocator> const> ConstPtr;

}; // struct LeanMap_

typedef ::robot_msg::LeanMap_<std::allocator<void> > LeanMap;

typedef boost::shared_ptr< ::robot_msg::LeanMap > LeanMapPtr;
typedef boost::shared_ptr< ::robot_msg::LeanMap const> LeanMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::LeanMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::LeanMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::LeanMap_<ContainerAllocator1> & lhs, const ::robot_msg::LeanMap_<ContainerAllocator2> & rhs)
{
  return lhs.resolution == rhs.resolution &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::LeanMap_<ContainerAllocator1> & lhs, const ::robot_msg::LeanMap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::LeanMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::LeanMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::LeanMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::LeanMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::LeanMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::LeanMap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::LeanMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5d9161024fc3ea9720ca822a0ae9d91";
  }

  static const char* value(const ::robot_msg::LeanMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5d9161024fc3ea9ULL;
  static const uint64_t static_value2 = 0x720ca822a0ae9d91ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::LeanMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/LeanMap";
  }

  static const char* value(const ::robot_msg::LeanMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::LeanMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 resolution\n"
"uint32 width\n"
"uint32 height\n"
"int8[] data\n"
;
  }

  static const char* value(const ::robot_msg::LeanMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::LeanMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resolution);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LeanMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::LeanMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::LeanMap_<ContainerAllocator>& v)
  {
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_LEANMAP_H
