// Generated by gencpp from file robot_msg/MapLoading.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_MAPLOADING_H
#define ROBOT_MSG_MESSAGE_MAPLOADING_H

#include <ros/service_traits.h>


#include <robot_msg/MapLoadingRequest.h>
#include <robot_msg/MapLoadingResponse.h>


namespace robot_msg
{

struct MapLoading
{

typedef MapLoadingRequest Request;
typedef MapLoadingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapLoading
} // namespace robot_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msg::MapLoading > {
  static const char* value()
  {
    return "9c408861d9ae9ea33255ca346b01a6f8";
  }

  static const char* value(const ::robot_msg::MapLoading&) { return value(); }
};

template<>
struct DataType< ::robot_msg::MapLoading > {
  static const char* value()
  {
    return "robot_msg/MapLoading";
  }

  static const char* value(const ::robot_msg::MapLoading&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msg::MapLoadingRequest> should match
// service_traits::MD5Sum< ::robot_msg::MapLoading >
template<>
struct MD5Sum< ::robot_msg::MapLoadingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::MapLoading >::value();
  }
  static const char* value(const ::robot_msg::MapLoadingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::MapLoadingRequest> should match
// service_traits::DataType< ::robot_msg::MapLoading >
template<>
struct DataType< ::robot_msg::MapLoadingRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msg::MapLoading >::value();
  }
  static const char* value(const ::robot_msg::MapLoadingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msg::MapLoadingResponse> should match
// service_traits::MD5Sum< ::robot_msg::MapLoading >
template<>
struct MD5Sum< ::robot_msg::MapLoadingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::MapLoading >::value();
  }
  static const char* value(const ::robot_msg::MapLoadingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::MapLoadingResponse> should match
// service_traits::DataType< ::robot_msg::MapLoading >
template<>
struct DataType< ::robot_msg::MapLoadingResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msg::MapLoading >::value();
  }
  static const char* value(const ::robot_msg::MapLoadingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_MAPLOADING_H
