// Generated by gencpp from file robot_msg/RestrictArray.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_RESTRICTARRAY_H
#define ROBOT_MSG_MESSAGE_RESTRICTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_msg/Restrict.h>

namespace robot_msg
{
template <class ContainerAllocator>
struct RestrictArray_
{
  typedef RestrictArray_<ContainerAllocator> Type;

  RestrictArray_()
    : virtual_walls()  {
    }
  RestrictArray_(const ContainerAllocator& _alloc)
    : virtual_walls(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robot_msg::Restrict_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::robot_msg::Restrict_<ContainerAllocator> >::other >  _virtual_walls_type;
  _virtual_walls_type virtual_walls;





  typedef boost::shared_ptr< ::robot_msg::RestrictArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::RestrictArray_<ContainerAllocator> const> ConstPtr;

}; // struct RestrictArray_

typedef ::robot_msg::RestrictArray_<std::allocator<void> > RestrictArray;

typedef boost::shared_ptr< ::robot_msg::RestrictArray > RestrictArrayPtr;
typedef boost::shared_ptr< ::robot_msg::RestrictArray const> RestrictArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::RestrictArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::RestrictArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::RestrictArray_<ContainerAllocator1> & lhs, const ::robot_msg::RestrictArray_<ContainerAllocator2> & rhs)
{
  return lhs.virtual_walls == rhs.virtual_walls;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::RestrictArray_<ContainerAllocator1> & lhs, const ::robot_msg::RestrictArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::RestrictArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::RestrictArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::RestrictArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::RestrictArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::RestrictArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::RestrictArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::RestrictArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d730ec60ad06fc558c39d4bf2bff233e";
  }

  static const char* value(const ::robot_msg::RestrictArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd730ec60ad06fc55ULL;
  static const uint64_t static_value2 = 0x8c39d4bf2bff233eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::RestrictArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/RestrictArray";
  }

  static const char* value(const ::robot_msg::RestrictArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::RestrictArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# msg definition\n"
"\n"
"# virtual walls e.g.\n"
"\n"
"robot_msg/Restrict[]  virtual_walls                # 虚拟墙描述\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot_msg/Restrict\n"
"# msg definition\n"
"\n"
"# virtual walls e.g.\n"
"\n"
"int32                   id          # id\n"
"geometry_msgs/Polygon   polygon       # Clockwise\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::robot_msg::RestrictArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::RestrictArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.virtual_walls);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RestrictArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::RestrictArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::RestrictArray_<ContainerAllocator>& v)
  {
    s << indent << "virtual_walls[]" << std::endl;
    for (size_t i = 0; i < v.virtual_walls.size(); ++i)
    {
      s << indent << "  virtual_walls[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_msg::Restrict_<ContainerAllocator> >::stream(s, indent + "    ", v.virtual_walls[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_RESTRICTARRAY_H
