// Generated by gencpp from file robot_msg/Restrict.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_RESTRICT_H
#define ROBOT_MSG_MESSAGE_RESTRICT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Polygon.h>

namespace robot_msg
{
template <class ContainerAllocator>
struct Restrict_
{
  typedef Restrict_<ContainerAllocator> Type;

  Restrict_()
    : id(0)
    , polygon()  {
    }
  Restrict_(const ContainerAllocator& _alloc)
    : id(0)
    , polygon(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _polygon_type;
  _polygon_type polygon;





  typedef boost::shared_ptr< ::robot_msg::Restrict_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::Restrict_<ContainerAllocator> const> ConstPtr;

}; // struct Restrict_

typedef ::robot_msg::Restrict_<std::allocator<void> > Restrict;

typedef boost::shared_ptr< ::robot_msg::Restrict > RestrictPtr;
typedef boost::shared_ptr< ::robot_msg::Restrict const> RestrictConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::Restrict_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::Restrict_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::Restrict_<ContainerAllocator1> & lhs, const ::robot_msg::Restrict_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.polygon == rhs.polygon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::Restrict_<ContainerAllocator1> & lhs, const ::robot_msg::Restrict_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::Restrict_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::Restrict_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::Restrict_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::Restrict_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::Restrict_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::Restrict_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::Restrict_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42ff449c102e05ed9295a8972a24ec0a";
  }

  static const char* value(const ::robot_msg::Restrict_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42ff449c102e05edULL;
  static const uint64_t static_value2 = 0x9295a8972a24ec0aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::Restrict_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/Restrict";
  }

  static const char* value(const ::robot_msg::Restrict_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::Restrict_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# msg definition\n"
"\n"
"# virtual walls e.g.\n"
"\n"
"int32                   id          # id\n"
"geometry_msgs/Polygon   polygon       # Clockwise\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::robot_msg::Restrict_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::Restrict_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.polygon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Restrict_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::Restrict_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::Restrict_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "polygon: ";
    s << std::endl;
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.polygon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_RESTRICT_H
