// Generated by gencpp from file robot_msg/SaveFramesRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_SAVEFRAMESREQUEST_H
#define ROBOT_MSG_MESSAGE_SAVEFRAMESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msg
{
template <class ContainerAllocator>
struct SaveFramesRequest_
{
  typedef SaveFramesRequest_<ContainerAllocator> Type;

  SaveFramesRequest_()
    : save_flag(false)  {
    }
  SaveFramesRequest_(const ContainerAllocator& _alloc)
    : save_flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _save_flag_type;
  _save_flag_type save_flag;





  typedef boost::shared_ptr< ::robot_msg::SaveFramesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::SaveFramesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveFramesRequest_

typedef ::robot_msg::SaveFramesRequest_<std::allocator<void> > SaveFramesRequest;

typedef boost::shared_ptr< ::robot_msg::SaveFramesRequest > SaveFramesRequestPtr;
typedef boost::shared_ptr< ::robot_msg::SaveFramesRequest const> SaveFramesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::SaveFramesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::SaveFramesRequest_<ContainerAllocator1> & lhs, const ::robot_msg::SaveFramesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.save_flag == rhs.save_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::SaveFramesRequest_<ContainerAllocator1> & lhs, const ::robot_msg::SaveFramesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::SaveFramesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::SaveFramesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::SaveFramesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddeab5f16c6a569b8a3051f83ab73fd4";
  }

  static const char* value(const ::robot_msg::SaveFramesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddeab5f16c6a569bULL;
  static const uint64_t static_value2 = 0x8a3051f83ab73fd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/SaveFramesRequest";
  }

  static const char* value(const ::robot_msg::SaveFramesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool save_flag  # true-发送保存帧请求；false-发送停止保存帧请求\n"
;
  }

  static const char* value(const ::robot_msg::SaveFramesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.save_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveFramesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::SaveFramesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::SaveFramesRequest_<ContainerAllocator>& v)
  {
    s << indent << "save_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.save_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_SAVEFRAMESREQUEST_H
