// Generated by gencpp from file robot_msg/SetMapRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_SETMAPREQUEST_H
#define ROBOT_MSG_MESSAGE_SETMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <robot_msg/Restrict.h>

namespace robot_msg
{
template <class ContainerAllocator>
struct SetMapRequest_
{
  typedef SetMapRequest_<ContainerAllocator> Type;

  SetMapRequest_()
    : cmd()
    , name()
    , pose()
    , virtual_wall()  {
    }
  SetMapRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)
    , name(_alloc)
    , pose(_alloc)
    , virtual_wall(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::robot_msg::Restrict_<ContainerAllocator>  _virtual_wall_type;
  _virtual_wall_type virtual_wall;





  typedef boost::shared_ptr< ::robot_msg::SetMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::SetMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMapRequest_

typedef ::robot_msg::SetMapRequest_<std::allocator<void> > SetMapRequest;

typedef boost::shared_ptr< ::robot_msg::SetMapRequest > SetMapRequestPtr;
typedef boost::shared_ptr< ::robot_msg::SetMapRequest const> SetMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::SetMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::SetMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::SetMapRequest_<ContainerAllocator1> & lhs, const ::robot_msg::SetMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.name == rhs.name &&
    lhs.pose == rhs.pose &&
    lhs.virtual_wall == rhs.virtual_wall;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::SetMapRequest_<ContainerAllocator1> & lhs, const ::robot_msg::SetMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::SetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::SetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::SetMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::SetMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::SetMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::SetMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "116a254963ea83aa307bd4da3e81f397";
  }

  static const char* value(const ::robot_msg::SetMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x116a254963ea83aaULL;
  static const uint64_t static_value2 = 0x307bd4da3e81f397ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/SetMapRequest";
  }

  static const char* value(const ::robot_msg::SetMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::SetMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# srv definition\n"
"\n"
"#request constants\n"
"\n"
"#   \"building_map\",         构建地图\n"
"#   \"save_map\",             保存地图\n"
"#   \"switch_map\",           加载地图\n"
"#   \"delete_map\",           删除地图\n"
"#   \"add_virtual_wall\"      添加虚拟墙\n"
"#   \"remove_virtual_wall\"   移除虚拟墙\n"
"\n"
"#request fields\n"
"string                  cmd                 # 地图操作命令\n"
"string                  name                # 地图名称\n"
"geometry_msgs/Vector3   pose                # 加载地图的初始位姿\n"
"robot_msg/Restrict      virtual_wall        # 设置虚拟墙\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: robot_msg/Restrict\n"
"# msg definition\n"
"\n"
"# virtual walls e.g.\n"
"\n"
"int32                   id          # id\n"
"geometry_msgs/Polygon   polygon       # Clockwise\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::robot_msg::SetMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::SetMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.name);
      stream.next(m.pose);
      stream.next(m.virtual_wall);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::SetMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::SetMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "virtual_wall: ";
    s << std::endl;
    Printer< ::robot_msg::Restrict_<ContainerAllocator> >::stream(s, indent + "  ", v.virtual_wall);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_SETMAPREQUEST_H
