// Generated by gencpp from file robot_msg/SetMap.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_SETMAP_H
#define ROBOT_MSG_MESSAGE_SETMAP_H

#include <ros/service_traits.h>


#include <robot_msg/SetMapRequest.h>
#include <robot_msg/SetMapResponse.h>


namespace robot_msg
{

struct SetMap
{

typedef SetMapRequest Request;
typedef SetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMap
} // namespace robot_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msg::SetMap > {
  static const char* value()
  {
    return "7dbd698048cc10e20abf3ca951e09510";
  }

  static const char* value(const ::robot_msg::SetMap&) { return value(); }
};

template<>
struct DataType< ::robot_msg::SetMap > {
  static const char* value()
  {
    return "robot_msg/SetMap";
  }

  static const char* value(const ::robot_msg::SetMap&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msg::SetMapRequest> should match
// service_traits::MD5Sum< ::robot_msg::SetMap >
template<>
struct MD5Sum< ::robot_msg::SetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::SetMap >::value();
  }
  static const char* value(const ::robot_msg::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::SetMapRequest> should match
// service_traits::DataType< ::robot_msg::SetMap >
template<>
struct DataType< ::robot_msg::SetMapRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msg::SetMap >::value();
  }
  static const char* value(const ::robot_msg::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msg::SetMapResponse> should match
// service_traits::MD5Sum< ::robot_msg::SetMap >
template<>
struct MD5Sum< ::robot_msg::SetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::SetMap >::value();
  }
  static const char* value(const ::robot_msg::SetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::SetMapResponse> should match
// service_traits::DataType< ::robot_msg::SetMap >
template<>
struct DataType< ::robot_msg::SetMapResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msg::SetMap >::value();
  }
  static const char* value(const ::robot_msg::SetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_SETMAP_H
