// Generated by gencpp from file robot_msg/SetRestrict.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_SETRESTRICT_H
#define ROBOT_MSG_MESSAGE_SETRESTRICT_H

#include <ros/service_traits.h>


#include <robot_msg/SetRestrictRequest.h>
#include <robot_msg/SetRestrictResponse.h>


namespace robot_msg
{

struct SetRestrict
{

typedef SetRestrictRequest Request;
typedef SetRestrictResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRestrict
} // namespace robot_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msg::SetRestrict > {
  static const char* value()
  {
    return "1f3913cc9796519611b8018d97267e81";
  }

  static const char* value(const ::robot_msg::SetRestrict&) { return value(); }
};

template<>
struct DataType< ::robot_msg::SetRestrict > {
  static const char* value()
  {
    return "robot_msg/SetRestrict";
  }

  static const char* value(const ::robot_msg::SetRestrict&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msg::SetRestrictRequest> should match
// service_traits::MD5Sum< ::robot_msg::SetRestrict >
template<>
struct MD5Sum< ::robot_msg::SetRestrictRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::SetRestrict >::value();
  }
  static const char* value(const ::robot_msg::SetRestrictRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::SetRestrictRequest> should match
// service_traits::DataType< ::robot_msg::SetRestrict >
template<>
struct DataType< ::robot_msg::SetRestrictRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msg::SetRestrict >::value();
  }
  static const char* value(const ::robot_msg::SetRestrictRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msg::SetRestrictResponse> should match
// service_traits::MD5Sum< ::robot_msg::SetRestrict >
template<>
struct MD5Sum< ::robot_msg::SetRestrictResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msg::SetRestrict >::value();
  }
  static const char* value(const ::robot_msg::SetRestrictResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msg::SetRestrictResponse> should match
// service_traits::DataType< ::robot_msg::SetRestrict >
template<>
struct DataType< ::robot_msg::SetRestrictResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msg::SetRestrict >::value();
  }
  static const char* value(const ::robot_msg::SetRestrictResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_SETRESTRICT_H
