// Auto-generated. Do not edit!

// (in-package robot_msg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let auto_dockActionGoal = require('./auto_dockActionGoal.js');
let auto_dockActionResult = require('./auto_dockActionResult.js');
let auto_dockActionFeedback = require('./auto_dockActionFeedback.js');

//-----------------------------------------------------------

class auto_dockAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new auto_dockActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new auto_dockActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new auto_dockActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type auto_dockAction
    // Serialize message field [action_goal]
    bufferOffset = auto_dockActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = auto_dockActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = auto_dockActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type auto_dockAction
    let len;
    let data = new auto_dockAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = auto_dockActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = auto_dockActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = auto_dockActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += auto_dockActionGoal.getMessageSize(object.action_goal);
    length += auto_dockActionResult.getMessageSize(object.action_result);
    length += auto_dockActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_msg/auto_dockAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9e98f2058ad2cc4e7559f47f7c2c4b81';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    auto_dockActionGoal action_goal
    auto_dockActionResult action_result
    auto_dockActionFeedback action_feedback
    
    ================================================================================
    MSG: robot_msg/auto_dockActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    auto_dockGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: robot_msg/auto_dockGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # 定义目标goal
    bool dock_ctrl  # 对接控制    true 去充电 false 取消充电
    
    
    ================================================================================
    MSG: robot_msg/auto_dockActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    auto_dockResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: robot_msg/auto_dockResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result 回充结果
    bool dock_result       # 成功１　失败０
    
    
    ================================================================================
    MSG: robot_msg/auto_dockActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    auto_dockFeedback feedback
    
    ================================================================================
    MSG: robot_msg/auto_dockFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    # constants state enum
    uint8 NONE              = 0 #初始化状态
    uint8 SEARCHING_STATION = 1 # 1-寻找充电桩
    uint8 DOCKING_STATION   = 2 # 2-对接中
    uint8 DOCKING_SUCCESS   = 3 # 3-对接成功
    uint8 SEPERATING        = 4 # 4-脱离中
    uint8 SEPERATING_DONE   = 5 # 5-脱离成功
    uint8 SEARCHING_FAILURE = 6 # 6-失败-未找到充电桩
    uint8 DOCKING_FAILURE   = 7 # 7-失败-对接失败
    uint8 SEPERAT_FAILURE   = 8 # 8-失败-脱离失败
    uint8 CANCLED           = 9 # 9-成功-动作被取消
    
    uint8 dock_feedback
    string dock_feedback_text
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new auto_dockAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = auto_dockActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new auto_dockActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = auto_dockActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new auto_dockActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = auto_dockActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new auto_dockActionFeedback()
    }

    return resolved;
    }
};

module.exports = auto_dockAction;
