// Auto-generated. Do not edit!

// (in-package robot_msg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class auto_dockFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.dock_feedback = null;
      this.dock_feedback_text = null;
    }
    else {
      if (initObj.hasOwnProperty('dock_feedback')) {
        this.dock_feedback = initObj.dock_feedback
      }
      else {
        this.dock_feedback = 0;
      }
      if (initObj.hasOwnProperty('dock_feedback_text')) {
        this.dock_feedback_text = initObj.dock_feedback_text
      }
      else {
        this.dock_feedback_text = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type auto_dockFeedback
    // Serialize message field [dock_feedback]
    bufferOffset = _serializer.uint8(obj.dock_feedback, buffer, bufferOffset);
    // Serialize message field [dock_feedback_text]
    bufferOffset = _serializer.string(obj.dock_feedback_text, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type auto_dockFeedback
    let len;
    let data = new auto_dockFeedback(null);
    // Deserialize message field [dock_feedback]
    data.dock_feedback = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [dock_feedback_text]
    data.dock_feedback_text = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.dock_feedback_text.length;
    return length + 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_msg/auto_dockFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3a59dd52073742794fd7cc52d1917f2d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    # constants state enum
    uint8 NONE              = 0 #初始化状态
    uint8 SEARCHING_STATION = 1 # 1-寻找充电桩
    uint8 DOCKING_STATION   = 2 # 2-对接中
    uint8 DOCKING_SUCCESS   = 3 # 3-对接成功
    uint8 SEPERATING        = 4 # 4-脱离中
    uint8 SEPERATING_DONE   = 5 # 5-脱离成功
    uint8 SEARCHING_FAILURE = 6 # 6-失败-未找到充电桩
    uint8 DOCKING_FAILURE   = 7 # 7-失败-对接失败
    uint8 SEPERAT_FAILURE   = 8 # 8-失败-脱离失败
    uint8 CANCLED           = 9 # 9-成功-动作被取消
    
    uint8 dock_feedback
    string dock_feedback_text
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new auto_dockFeedback(null);
    if (msg.dock_feedback !== undefined) {
      resolved.dock_feedback = msg.dock_feedback;
    }
    else {
      resolved.dock_feedback = 0
    }

    if (msg.dock_feedback_text !== undefined) {
      resolved.dock_feedback_text = msg.dock_feedback_text;
    }
    else {
      resolved.dock_feedback_text = ''
    }

    return resolved;
    }
};

// Constants for message
auto_dockFeedback.Constants = {
  NONE: 0,
  SEARCHING_STATION: 1,
  DOCKING_STATION: 2,
  DOCKING_SUCCESS: 3,
  SEPERATING: 4,
  SEPERATING_DONE: 5,
  SEARCHING_FAILURE: 6,
  DOCKING_FAILURE: 7,
  SEPERAT_FAILURE: 8,
  CANCLED: 9,
}

module.exports = auto_dockFeedback;
