(cl:defpackage forward_server-msg
  (:use )
  (:export
   "<FORWARDACTION>"
   "FORWARDACTION"
   "<FORWARDACTIONFEEDBACK>"
   "FORWARDACTIONFEEDBACK"
   "<FORWARDACTIONGOAL>"
   "FORWARDACTIONGOAL"
   "<FORWARDACTIONRESULT>"
   "FORWARDACTIONRESULT"
   "<FORWARDFEEDBACK>"
   "FORWARDFEEDBACK"
   "<FORWARDGOAL>"
   "FORWARDGOAL"
   "<FORWARDRESULT>"
   "FORWARDRESULT"
  ))

