(cl:in-package robot_msg-msg)
(cl:export '(CONNECTED-VAL
          CONNECTED
          BASE_DEVICE_STATE-VAL
          BASE_DEVICE_STATE
          CLIFF_LEFT-VAL
          CLIFF_LEFT
          CLIFF_FRONT_LEFT-VAL
          CLIFF_FRONT_LEFT
          CLIFF_FRONT_RIGHT-VAL
          CLIFF_FRONT_RIGHT
          CLIFF_RIGHT-VAL
          CLIFF_RIGHT
          BUMP_STATE_LEFT-VAL
          BUMP_STATE_LEFT
          BUMP_STATE_RIGHT-VAL
          BUMP_STATE_RIGHT
          CHARGINGVOL-VAL
          CHARGINGVOL
          CHARGINGSTATE-VAL
          CHARGINGSTATE
          MOTOR_LEFT_ERR_CODE-VAL
          MOTOR_LEFT_ERR_CODE
          MOTOR_RIGHT_ERR_CODE-VAL
          MOTOR_RIGHT_ERR_CODE
          BUMP_ENABLE-VAL
          BUMP_ENABLE
          CLIFF_ENABLE-VAL
          CLIFF_ENABLE
))