; Auto-generated. Do not edit!


(cl:in-package robot_msg-msg)


;//! \htmlinclude auto_dockFeedback.msg.html

(cl:defclass <auto_dockFeedback> (roslisp-msg-protocol:ros-message)
  ((dock_feedback
    :reader dock_feedback
    :initarg :dock_feedback
    :type cl:fixnum
    :initform 0)
   (dock_feedback_text
    :reader dock_feedback_text
    :initarg :dock_feedback_text
    :type cl:string
    :initform ""))
)

(cl:defclass auto_dockFeedback (<auto_dockFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <auto_dockFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'auto_dockFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_msg-msg:<auto_dockFeedback> is deprecated: use robot_msg-msg:auto_dockFeedback instead.")))

(cl:ensure-generic-function 'dock_feedback-val :lambda-list '(m))
(cl:defmethod dock_feedback-val ((m <auto_dockFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msg-msg:dock_feedback-val is deprecated.  Use robot_msg-msg:dock_feedback instead.")
  (dock_feedback m))

(cl:ensure-generic-function 'dock_feedback_text-val :lambda-list '(m))
(cl:defmethod dock_feedback_text-val ((m <auto_dockFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_msg-msg:dock_feedback_text-val is deprecated.  Use robot_msg-msg:dock_feedback_text instead.")
  (dock_feedback_text m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<auto_dockFeedback>)))
    "Constants for message type '<auto_dockFeedback>"
  '((:NONE . 0)
    (:SEARCHING_STATION . 1)
    (:DOCKING_STATION . 2)
    (:DOCKING_SUCCESS . 3)
    (:SEPERATING . 4)
    (:SEPERATING_DONE . 5)
    (:SEARCHING_FAILURE . 6)
    (:DOCKING_FAILURE . 7)
    (:SEPERAT_FAILURE . 8)
    (:CANCLED . 9))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'auto_dockFeedback)))
    "Constants for message type 'auto_dockFeedback"
  '((:NONE . 0)
    (:SEARCHING_STATION . 1)
    (:DOCKING_STATION . 2)
    (:DOCKING_SUCCESS . 3)
    (:SEPERATING . 4)
    (:SEPERATING_DONE . 5)
    (:SEARCHING_FAILURE . 6)
    (:DOCKING_FAILURE . 7)
    (:SEPERAT_FAILURE . 8)
    (:CANCLED . 9))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <auto_dockFeedback>) ostream)
  "Serializes a message object of type '<auto_dockFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dock_feedback)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'dock_feedback_text))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'dock_feedback_text))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <auto_dockFeedback>) istream)
  "Deserializes a message object of type '<auto_dockFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dock_feedback)) (cl:read-byte istream))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'dock_feedback_text) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'dock_feedback_text) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<auto_dockFeedback>)))
  "Returns string type for a message object of type '<auto_dockFeedback>"
  "robot_msg/auto_dockFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'auto_dockFeedback)))
  "Returns string type for a message object of type 'auto_dockFeedback"
  "robot_msg/auto_dockFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<auto_dockFeedback>)))
  "Returns md5sum for a message object of type '<auto_dockFeedback>"
  "3a59dd52073742794fd7cc52d1917f2d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'auto_dockFeedback)))
  "Returns md5sum for a message object of type 'auto_dockFeedback"
  "3a59dd52073742794fd7cc52d1917f2d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<auto_dockFeedback>)))
  "Returns full string definition for message of type '<auto_dockFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%# constants state enum~%uint8 NONE              = 0 #初始化状态~%uint8 SEARCHING_STATION = 1 # 1-寻找充电桩~%uint8 DOCKING_STATION   = 2 # 2-对接中~%uint8 DOCKING_SUCCESS   = 3 # 3-对接成功~%uint8 SEPERATING        = 4 # 4-脱离中~%uint8 SEPERATING_DONE   = 5 # 5-脱离成功~%uint8 SEARCHING_FAILURE = 6 # 6-失败-未找到充电桩~%uint8 DOCKING_FAILURE   = 7 # 7-失败-对接失败~%uint8 SEPERAT_FAILURE   = 8 # 8-失败-脱离失败~%uint8 CANCLED           = 9 # 9-成功-动作被取消~%~%uint8 dock_feedback~%string dock_feedback_text~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'auto_dockFeedback)))
  "Returns full string definition for message of type 'auto_dockFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%# constants state enum~%uint8 NONE              = 0 #初始化状态~%uint8 SEARCHING_STATION = 1 # 1-寻找充电桩~%uint8 DOCKING_STATION   = 2 # 2-对接中~%uint8 DOCKING_SUCCESS   = 3 # 3-对接成功~%uint8 SEPERATING        = 4 # 4-脱离中~%uint8 SEPERATING_DONE   = 5 # 5-脱离成功~%uint8 SEARCHING_FAILURE = 6 # 6-失败-未找到充电桩~%uint8 DOCKING_FAILURE   = 7 # 7-失败-对接失败~%uint8 SEPERAT_FAILURE   = 8 # 8-失败-脱离失败~%uint8 CANCLED           = 9 # 9-成功-动作被取消~%~%uint8 dock_feedback~%string dock_feedback_text~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <auto_dockFeedback>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'dock_feedback_text))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <auto_dockFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'auto_dockFeedback
    (cl:cons ':dock_feedback (dock_feedback msg))
    (cl:cons ':dock_feedback_text (dock_feedback_text msg))
))
