// Auto-generated. Do not edit!

// (in-package forward_server.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class forwardGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.line = null;
      this.line_velocity = null;
      this.time_out = null;
    }
    else {
      if (initObj.hasOwnProperty('line')) {
        this.line = initObj.line
      }
      else {
        this.line = 0.0;
      }
      if (initObj.hasOwnProperty('line_velocity')) {
        this.line_velocity = initObj.line_velocity
      }
      else {
        this.line_velocity = 0.0;
      }
      if (initObj.hasOwnProperty('time_out')) {
        this.time_out = initObj.time_out
      }
      else {
        this.time_out = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type forwardGoal
    // Serialize message field [line]
    bufferOffset = _serializer.float64(obj.line, buffer, bufferOffset);
    // Serialize message field [line_velocity]
    bufferOffset = _serializer.float64(obj.line_velocity, buffer, bufferOffset);
    // Serialize message field [time_out]
    bufferOffset = _serializer.float64(obj.time_out, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type forwardGoal
    let len;
    let data = new forwardGoal(null);
    // Deserialize message field [line]
    data.line = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [line_velocity]
    data.line_velocity = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [time_out]
    data.time_out = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 24;
  }

  static datatype() {
    // Returns string type for a message object
    return 'forward_server/forwardGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1ea14902e630c8a1c9802214171cc9f0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float64 line
    float64 line_velocity
    float64 time_out
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new forwardGoal(null);
    if (msg.line !== undefined) {
      resolved.line = msg.line;
    }
    else {
      resolved.line = 0.0
    }

    if (msg.line_velocity !== undefined) {
      resolved.line_velocity = msg.line_velocity;
    }
    else {
      resolved.line_velocity = 0.0
    }

    if (msg.time_out !== undefined) {
      resolved.time_out = msg.time_out;
    }
    else {
      resolved.time_out = 0.0
    }

    return resolved;
    }
};

module.exports = forwardGoal;
